paths:
    migrations: %%PHINX_CONFIG_DIR%%/app/phinx/migrations

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: estimator
        user: estimator
        pass: estimator
        port: 3306
        charset: utf8

    development:
        adapter: mysql
        host: localhost
        name: estimator
        user: estimator
        pass: estimator
        port: 3306
        charset: utf8

    testing:
        adapter: mysql
        host: localhost
        name: estimator
        user: estimator
        pass: estimator
        port: 3306
        charset: utf8
